cloudfoundry-community/logsearch-for-cloudfoundry

logsearch-for-cloudfoundry-boshrelease/packages/firehose-to-syslog/packaging

Also, removes the (now) unnecessary fetching of the $REPO_DIR/Godeps/_workspace/src/golang.org/x/net dependancy during compilation

Update to firehose-to-syslog v0.0.2

---

README.md
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/monit
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/spec
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/bin/cf_app_details_cache_ctl
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/bin/monit_debugger
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/data/properties.sh.erb
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/helpers/ctl_setup.sh
logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/helpers/ctl_utils.sh
src/logstash-filters/snippets/doppler.conf
target/logstash-filters-default.conf
test/logstash-filters/snippets/doppler-spec.rb
test/logstash-filters/snippets/loggregator-spec.rb
test/logstash-filters/snippets/vcap-spec.rb

Doppler tags all logs with a unique `cf_app_id` UUID, eg:
```
{"cf_app_id":"afc7d161-b5d5-44f2-a2c8-63870ff8f2db","level":"info","message_type":"OUT","msg":"goexample.apps.54.183.203.97.xip.io - [01/04/2015:10:22:50 +0000] \"GET / HTTP/1.1\" 200 7 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\" 10.10.2.6:60637 x_forwarded_for:\"46.165.195.139, 10.10.2.6\" vcap_request_id:9f598459-f756-4ea4-58e5-e9f212ff328f response_time:0.002463550 app_id:afc7d161-b5d5-44f2-a2c8-63870ff8f2db\n","source_instance":"0","source_type":"RTR","time":"2015-04-01T10:22:50Z"}
```
UUIDs make for crappy dashboards:
We should be decorating each log with:
* `cf_app_name`
* `cf_space_id` and `cf_space_name`
* `cf_org_id` and `cf_org_name`
so we can make human readable dashboards that can be segregated …

Decorate doppler logs with App name / space / org

---

src/cf-app-logs/.gitignore
src/cf-app-logs/manifest.yml
src/cf-app-logs/pom.xml
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/ElasticSearchRequestAddTenantFilterZuulFilter.java
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/ElasticsearchQueryModifier.java
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/LogsearchForCloudFoundry.java
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/SimpleUAAClient.java
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/TenantAliasCreator.java
src/cf-app-logs/src/main/java/logsearchForCloudFoundry/UserInfo.java
src/cf-app-logs/src/main/resources/application.yml
src/cf-app-logs/src/test/java/logsearchForCloudFoundry/ElasticsearchQueryModifierTests.java

The PR implements a proxy for Kibana4 based on Spring Cloud's OAuth2 and Zuul modules.
It intercepts all Kibana4 requests, logs the user in via CF's UAA component, ensures that aliases for the user exist on all ES indices and contain appropriate space_id filters, and rewrites all ES requests so that the are made against the user's aliases rather than the underlying indices.
The effect is that all queries made by the user return only data for apps in spaces they are a member of.
The proxy is indented to be deployed as an app in the CF cluster

Add multi-tenancy via cf-app-logs Kibana proxy

---

logsearch-for-cloudfoundry-boshrelease/templates/stub.yml

Hello,
During my tests, the property cloudfoundry.firehose_events was not merged by spiff using make_manifest script.
I have added to stub.yml the default value for this property. With this, we can define this value in a sub-template...

Fix: cloudfoundry.firehose_events not being merged by spiff

---

logsearch-for-cloudfoundry-boshrelease/config/blobs.yml
logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/spec
logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
logsearch-for-cloudfoundry-boshrelease/packages/firehose-to-syslog-java8/packaging
logsearch-for-cloudfoundry-boshrelease/packages/firehose-to-syslog-java8/spec
logsearch-for-cloudfoundry-boshrelease/packages/firehose-to-syslog-logstash/packaging
logsearch-for-cloudfoundry-boshrelease/packages/firehose-to-syslog-logstash/spec
logsearch-for-cloudfoundry-boshrelease/packages/java8/spec
logsearch-for-cloudfoundry-boshrelease/packages/logstash/spec

Prevent naming conflicts with core `logsearch-boshrelease` by renaming 
* `packages/logstash` -> `packages/firehose-to-syslog-logstash`
* `packages/java8` -> `packages/firehose-to-syslog-java8`
Also updates `packages/firehose-to-syslog-logstash` from logstash 1.5.0 to logstash 1.5.2
This addresses #45 and #63

Enable ingestor_cloudfoundry-firehose to be colocated with ingestors from core logsearch-boshrelease

---

logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana/spec
logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana/templates/config/manifest.yml

Enable configuring the CF memory and instances used by the Kibana dashboard.
```
push-kibana.app_memory:
description: "The Kibana log dashboard app memory quota"
default: 256M
push-kibana.app_instances:
description: "The Kibana log dashboard app number of instances"
default: 2
```

Configure app memory & instances

---

jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl

I faced the problem with updating ingestor_cloudfoundry-firehose job when I tested logsearch-for-cloudfoundry release using centos7 stemcells.
There is no –z option for ncat command in centos7. For –z we need openbsd-netcat package which was replaced with nmap-ncat in centos7.
```
nc: invalid option -- 'z'
```
Fix was tested against both Ubuntu and centos7 stemcells.

Centos7 stemcells support

---

generate_ingestor_manifest
ingestor-only.example.yml

Hi!
This PR adds the ability to generate different Elasticsearch [mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) for CF platform logs and CF application logs.
Mappings templates will provide @hannayurkevich in separate PR.
Thanks!

Elasticsearch mappings generation

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf

This is really useful to separate CF components logs from applications logs and store them in different indices.
So field [@metadata][index] is added to store index name. It is set to 'unparsed' on init. Then for application logs (those coming from firehose) we set it to 'app'. For parsed CF logs we set it to 'platform'.

Use different indices names for application logs and CF logs.

---

src/logsearch-config/src/logstash-filters/snippets/firehose.conf

This PR includes improvements made for application logs parsing (firehose.conf). The changes are described below. Please note that it is better to review the changes made in each commit rather than altogether because there were changes in formatting so the diff shows them in a not really convenient way.
The changes are the following:
Store application logs from different CF organizations / spaces to different indices (index name is defined by organization & space name). 
So app index name format is the following: app-${org}-${space}.
The PR includes parsing rules for JSON logs, Tomcat ([CONTAINER]) logs and Logback status logs.
And there are some minor fixes for application logs parsing: add event_type field if it is not passed, improve calculation of RTR logs level based on HTTP status, …

Add useful parsing rules for application logs

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/haproxy.conf

This PR adds parsing rules for haproxy job logs.
Haproxy is usually deployed with CF so it is useful to have it logs parsed.

Add parsing rules for haproxy

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/vcap.conf

General parsing rules for CF components' logs (vcap).
Additionally a vcap log is parsed as json (if in json format) and json properties are stored to vcap.* fields.

Add parsing rules for CF components (vcap) logs.

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf

This PR includes filters refactoring and minor rework. 
Refactoring includes changing snippets to follow the same structure - this makes them more readable and easier to edit.
Rework includes the following useful changes:
- Uaa, firehose: add @shipper.* fields; do not use old 'remove' option in mutate (replaced with 'remove_field'); lowercase UAA fields (UAA.* -> uaa.*).
- Firehose: replace unicode Null character (\0000) with "" and drop empty logs; fixed convertion of HTTP status code to @level.
- Common fields changes: uppercase @level field; rename field tags -> @tags.

Filters refactoring & rework

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/haproxy.conf
src/logsearch-config/src/logstash-filters/snippets/setup.conf
src/logsearch-config/src/logstash-filters/snippets/teardown.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf
src/logsearch-config/src/logstash-filters/snippets/undefined.conf
src/logsearch-config/src/logstash-filters/snippets/vcap.conf

This PR includes snippets refactoring that makes them having more convenient structure. The idea is to move common setup/teardown logic from all snippets to separate scripts to remove code duplication, make snippets more simple and readable.
Additionally 'setup' logic now includes rules for setting default values for `@level` and `@source.component` fields. It is possible that these fields are not set in snippets (because of wrong message format etc.) so we need to set the fields with default values, because the fields are significant some (those we want to see in Kibana table, search by etc.).
Also this PR includes additional processing rules of 'undefined' logs. Because we still need to parse CF logs that were not parsed by any of existing special snippets (uaa, vcap, etc.).
Changes …

Filters decomposition & additional processing

---

src/logsearch-config/src/logstash-filters/snippets/firehose.conf

1) Delete ContainerMetric special processing for now.
The rules look out-of-date so it makes sense to delete them for now as obsolete. 
Then we will add actual parsing rules for metrics after thorough investigation of possible formats and testing.
2) Fields refactoring: 
- lowercase RTR fields (RTR.* -> rtr.*); 
To be convenient with other fields.
- store application json fields to app.* fields; 
We need to distinguish between fields retrieved from application JSON message and other fields.
- rename firehose `@source.*` fields to avoid too long names (`[@source][org][name] -> [@source][org]`, etc.). 
Long names are not really useful in Kibana table (column header is longer than it's content).
3) Minor syntax fixes & additional fields presence checks (to avoid logstash warnings when …

Firehose parsing rework

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/haproxy.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf

At the moment some components (haproxy, uaa, app in JSON format) set `date` to their log events from specific `timestamp` fields that come together with log events. From the other hand for logs of other components (cloud_controller, hm9000, app in unknown format etc.) `date` is set from `syslog_timestamp` field which contains **metron_agent** timestamp (see https://github.com/logsearch/logsearch-boshrelease/blob/v201.0.16/src/logsearch-config/src/logstash-filters/snippets/syslog_standard.conf).
We need to be really sensible when setting `date` filter because it affects events distribution on a timeline in Kibana, in other words it specifies events order. So it really makes sense to set `date` to some unified time of events' lifecycle. The most appropriate is **metron_agent timestamp** …

Unify events timestamp by setting 'date' from metron_agent timestamp

---

src/logsearch-config/src/logstash-filters/default.conf.erb
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/haproxy.conf
src/logsearch-config/src/logstash-filters/snippets/teardown.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf
src/logsearch-config/src/logstash-filters/snippets/undefined.conf
src/logsearch-config/src/logstash-filters/snippets/vcap.conf

This PR includes filters & fields refactoring - cleanup useless fields, set mandatory fields (such as `@message`) for all log types, set missing fields etc.. The changes are the following:
Add `@input` field. Remove `syslog_pid`; Remove `[@job][host]`.
Set `[@source][host]` where it was missing.
Set `@message` for uaa.
Check JSON format more strictly (vcap).
Rename grok fail tag (undefined);
Remove square brackets where we access simple fields (e.g. use `@level` instead of `[@level]`).

Filters & fields refactoring

---

src/logsearch-config/bin/install-dependencies

Hi @axelaris !
This PR bumps Logstash version, it is necessary to run filters tests.
Thanks!

Bump Logstash version

---

.travis.yml

Hi @axelaris !
I added `.travis.yml` file, this file execute tests against logsearch-for-cloudfoundry filters which are located under `src/logsearch-config` folder.
Current tests are outdated, but @hannayurkevich already working on it. After the tests will be done we can enable Travis CI for the repo.
Thanks!

Enable logsearch-for-cloudfoundry to be tested on Travis CI

---

src/logsearch-config/src/logstash-filters/snippets/firehose.conf

Check for existence of `[@source][org]` and `[@source][space]` before constructing app index name. Otherwise we can get broken index name (if any of these fields are missing).

App index name fix

---

README.md
src/logsearch-config/bin/install-dependencies

Hi!
I fixed deprecated bin/plugin call. Instead of it we need to use `bin/logstash-plugin`.
Also i added the build status in readme page.
Thanks!

Fix deprecated bin/plugin call

---

src/logsearch-config/Rakefile
src/logsearch-config/bin/itest
src/logsearch-config/src/logstash-filters/snippets/firehose.conf
src/logsearch-config/src/logstash-filters/snippets/haproxy.conf
src/logsearch-config/src/logstash-filters/snippets/platform.conf
src/logsearch-config/src/logstash-filters/snippets/setup.conf
src/logsearch-config/src/logstash-filters/snippets/teardown.conf
src/logsearch-config/src/logstash-filters/snippets/uaa.conf
src/logsearch-config/src/logstash-filters/snippets/vcap.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/it/platform-it-spec.rb

1) Add support of integration tests. Integration tests run as part of all tests run and also can be started separately by executing bin/itest.
2) Add first integration tests (app and platform cases checking common fields).
3) Move parsing of common fields from snippets to setup.conf script. Snippets can override common fields with specific values if necessary.
4) Minor refactoring & comments.

Filters: Support of integration tests & first ITs & refactoring of common fields

---

generate_ingestor_manifest
src/logsearch-config/src/es-mappings/logs-template.json.erb

The mappings set to create *.raw not_analyzed fields for significant string fields (those fields that are supposed to be used in visualizations, aggregations etc).

Add mappings for not_analyzed .raw fields to be used in visualizations

---

packages/cf-cli/README.md
packages/cf-kibana/README.md
packages/golang/README.md
packages/golang/packaging

Add readme about packages sources in the same way as this done in major bosh projects. Here the example https://github.com/cloudfoundry/cf-release/tree/v238/packages/ruby-2.1.8

Add readme about packages sources

---

jobs/ingestor_cloudfoundry-firehose/spec
jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl

Hi @axelaris 
Firehose-to-syslog now supports different syslog protocols, this change was introduced in the next commit https://github.com/cloudfoundry-community/firehose-to-syslog/commit/10682878d02c225ce6392b2ea2e176e8a858cf6f. I updated `ingestor_cloudfoundry-firehose` job to support this property.
By default i set to still use tcp protocol.
Thanks!

Add syslog-protocol property to firehose-to-syslog package

---

jobs/cf-kibana/spec
jobs/cf-kibana/templates/kibana.yml.erb

Hi @axelaris 
After discussion with @hannayurkevich we decide to disable Kibana application logs by default.
I set `logging.silent: true` by default, here the reference to Kibana server properties:
https://www.elastic.co/guide/en/kibana/current/kibana-server-properties.html
Thanks!

Disable kibana app logs by default

---

jobs/cf-kibana/spec
jobs/cf-kibana/templates/manifest.yml.erb
src/kibana-cf_authentication/index.js

Set Kibana session expiration to a reasonable value of 12h. Make this value configurable.

Change Kibana session expiration

---

.gitmodules
src/logsearch-config/bin/build

Hi @axelaris 
I prefer to delete unused `logsearch-boshrelease` submodule. Since we are running all tests against `logsearch-for-cloudfoundry` filters we don't need to build logsearch-boshrelease filters using `vendor/logsearch-boshrelease/src/logsearch-config/bin/build`.

Remove unused logsearch-boshrelease submodule

---

src/logsearch-config/src/logstash-filters/snippets/app-log.conf
src/logsearch-config/src/logstash-filters/snippets/app.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/it_app_helper.rb
src/logsearch-config/test/logstash-filters/snippets/app-log-spec.rb
src/logsearch-config/test/logstash-filters/snippets/app-spec.rb

The thing is that Dea CF used to pass 'App' source_type in app logs (while passing other sources uppercase e.g. 'RTR', 'STG' etc.).
New Diego CF passes all sources as uppercase. So we uppercase [@source][component] after parsing source_type to make it conventional.
Update unit tests accordingly. Also add integration tests (testing LogMessage APP events) for both cases - Diego CF and Dea CF.
Do useful refactoring in app-it-spec.rb to make adding new tests to it easier.

Uppercase [@source][component] in app logs

---

templates/stub.logsearch-for-cloudfoundry.yml

Hi!
I updated stub, the current value for `elasticsearch_index_type` property outdated and should be changed to `"%{@type}"`.  
/cc @hannayurkevich

fix elasticsearch_index_type property

---

templates/logsearch-for-cf.example-with-uaa-auth.yml

Brings UAA template in line with `stub.logsearch-for-cloudfoundry.yml`.
h/t @linuxBozo

Add missing elastic properties to UAA template.

---

src/logsearch-config/src/logstash-filters/snippets/app.conf
src/logsearch-config/src/logstash-filters/snippets/platform.conf
src/logsearch-config/src/logstash-filters/snippets/setup.conf
src/logsearch-config/src/logstash-filters/snippets/teardown.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/it_app_helper.rb
src/logsearch-config/test/logstash-filters/snippets/platform-spec.rb
src/logsearch-config/test/logstash-filters/snippets/setup-spec.rb
src/logsearch-config/test/logstash-filters/snippets/teardown-spec.rb

Recent version of firehose-to-syslog passes new fields in json message: deployment, ip, job. Add parsing rules for these fields. Update tests accordingly.

Firehose parsing: parse new fields

---

src/logsearch-config/Rakefile

Hi @axelaris 
I have excluded `src` folder from path for YAML validation tests. `src` folder contains many `.travis.yaml` from submodules which we can skip.

Exclude src from YAML validation

---

src/logsearch-config/src/kibana4-dashboards/search/app-RTR-response_time_ms-lt-2000.json.erb
src/logsearch-config/src/kibana4-dashboards/search/app-RTR.json.erb
src/logsearch-config/src/kibana4-dashboards/visualization/App-names-and-response-times.json.erb
src/logsearch-config/src/kibana4-dashboards/visualization/HTTP-response-time-distribution-(-top-10-apps-).json.erb
src/logsearch-config/src/kibana4-dashboards/visualization/HTTP-response-times-(top-10-apps).json.erb
src/logsearch-config/src/kibana4-dashboards/visualization/HTTP-traffic-by-response_time_ms-(first-10-apps).json.erb
src/logsearch-config/src/kibana4-dashboards/visualization/HTTP-traffic-by-status-code.json.erb

"RTR" is capitalized in the kibana configs but not in the logstash templates. This patch updates the relevant kibana field names.
Part of #159.
cc @LinuxBozo

Update RTR field names to match logstash templates.

---

src/logsearch-config/src/logstash-filters/snippets/teardown.conf
src/logsearch-config/src/logstash-filters/snippets/vcap.conf
src/logsearch-config/test/filter_test_helpers.rb
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/it/platform-it-spec.rb
src/logsearch-config/test/logstash-filters/it/unparsed-it-spec.rb
src/logsearch-config/test/logstash-filters/it_app_helper.rb
src/logsearch-config/test/logstash-filters/it_platform_helper.rb
src/logsearch-config/test/logstash-filters/snippets/teardown-spec.rb
src/logsearch-config/test/logstash-filters/snippets/vcap-spec.rb

Different vcap components have different JSON messages, but they could contain JSON properties with the same name and different datatype. Elasticsearch doesn't allow fields with the same name to have different datatypes. In case of conflicts Logstash reports warning and conflicted values can be lost.
So to avoid such conflicts we now store parsed JSON to different target fields for different components. Name of target field is `@source.component` downcased and with '_' delimiter (naming is the same as in [logsearch-boshrelease json parsing](https://github.com/logsearch/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/if_it_looks_like_json.conf#L71)).

Store parsed json to a field with name of @source.component

---

templates/logsearch-for-cf.example-with-uaa-auth.yml

Without adding `logsearch-for-cloudfoundry-filters` to a job also using `elasticsearch_config` and setting the `templates` property, the expected elastic mapping template wouldn't be used, which could be hard to debug. Hypothetically 😉 .
cc @LinuxBozo

Add missing elastic mapping to UAA template.

---

jobs/cf-kibana/spec
jobs/cf-kibana/templates/kibana.yml.erb

Taken verbatim from
https://github.com/logsearch/logsearch-boshrelease/tree/v203.0.0/jobs/kibana.
While debugging a separate issue, I noticed that the kibana config is missing some potentially useful options, like choosing the default app--the default is "discover", which doesn't exist here. I just copied options that were available in logsearch-boshrelease and added them here.

Add templated options to kibana config.

---

jobs/create-uaa-client/spec
jobs/create-uaa-client/templates/bin/run

This application is a good use case for UAA auto-approve, to avoid
>  redundant and annoying requests to grant permission when there is not a reasonable need to ever deny them.
https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#clients
cc @LinuxBozo

Pass autoapprove option to UAA client create.

---

.gitmodules
jobs/smoke-tests/spec
jobs/smoke-tests/templates/config.json.erb
jobs/smoke-tests/templates/run.erb
packages/smoke-tests/packaging
packages/smoke-tests/spec
templates/stub.logsearch-for-cloudfoundry.yml

This PR introduces new job/package with the smoke-tests errand.
The smoke-tests workflow is next: Push the sample application which non stop generate logs -> Check via ElasticSearch API that logs for the sample application available in the APP index.
I believe that this is the easiest way to check the whole chain CF -> firehose-to-syslog -> ElasticSearch.

Add smoke-tests errand

---

config/blobs.yml
jobs/ingestor_cloudfoundry-firehose/spec
packages/golang/README.md
packages/golang/packaging
packages/golang/spec
src/logsearch-config/src/logstash-filters/snippets/app-error.conf
src/logsearch-config/src/logstash-filters/snippets/app-http.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/snippets/app-error-spec.rb
src/logsearch-config/test/logstash-filters/snippets/app-http-spec.rb

In this PR we switch to firehose-to-syslog 2.0.0 and go1.7.
Additionally it includes changes in parsing rules, because firehose-to-syslog v2.0.0 contains fixes in fields types/names, so parsing rules were updated accordingly. (fixes included in v2.0.0 are cloudfoundry-community/firehose-to-syslog#115 and cloudfoundry-community/firehose-to-syslog#114.)
Additionally, it sets default events subscription to 'LogMessage' so that we get only logs by default (no metrics).

Switch to firehose-to-syslog v2.0.0

---

jobs/upload-kibana-dashboards/spec
jobs/upload-kibana-dashboards/templates/bin/run
src/logsearch-config/Rakefile
templates/logsearch-for-cf.example-with-uaa-auth.yml
templates/stub.logsearch-for-cloudfoundry.yml

This patch adds an errand to upload kibana dashboards to elastic, since it looks like that step was dropped at some point (although it's still described in https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/src/kibana4-dashboards/README.md).
Written with @LinuxBozo

Add errand to upload kibana dashboards.

---

src/logsearch-config/src/logstash-filters/snippets/platform-vcap.conf
src/logsearch-config/test/logstash-filters/snippets/platform-vcap-spec.rb

Some CF components use numeric log levels: 0-DEBUG, 1-INFO, 2-ERROR, 3-FATAL.
When should translate such numeric values to string values accordingly. See original [issue](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/169) for details.
This PR has changes in platform vcap parsing to translate log level to string values as described above. Original value (converted to string) is used as a fallback for translate.
Plus new test cases in UTs  to check this logic.

Translate numeric @level to string value

---

src/logsearch-config/src/logstash-filters/snippets/app-logmessage-rtr.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/snippets/app-logmessage-rtr-spec.rb

Change App RTR logs parsing to set @message field as 
`%{[rtr][status]} %{[rtr][verb]} %{[rtr][path]} (%{[rtr][response_time_ms]} ms)`. 
Update tests accordingly.
(fix for issue https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/166)

Make rtr.@message more specific

---

jobs/ingestor_cloudfoundry-firehose/spec
jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl

Useful for avoiding password expiration on user accounts.
Depends on
https://github.com/cloudfoundry-community/firehose-to-syslog/pull/133
and https://github.com/cloudfoundry-community/go-cfclient/pull/36.

Support authentication via UAA client.

---

src/logsearch-config/src/kibana-objects/config/4.5.4.json.erb

Fix for https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/213.

Load default index to Kibana 4.5.4

---

docs/deployment.md
docs/features.md
jobs/cf-kibana/templates/manifest.yml.erb
jobs/create-uaa-client/spec
jobs/create-uaa-client/templates/bin/run
src/kibana-cf_authentication/index.js
templates/logsearch-for-cf.example-with-uaa-auth.yml

Redirect to Kibana /login after logout. Implemented using "redirect" parameter of UAA "/logout.do" endpoint. NOTE, that to work normally, redirects after logout should be enabled in UAA - https://github.com/cloudfoundry/uaa/blob/3.9.3/uaa/src/main/resources/login.yml#L38-L45.
Also add useful comments to kibana-cf_authentication plugin.

Add "redirect" parameter when calling UAA /logout.do during Kibana logout.

---

jobs/cf-kibana/spec
jobs/ingestor_cloudfoundry-firehose/spec
jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
templates/stub.ingestor-only.yml
templates/stub.logsearch-for-cf.cf-kibana.yml
templates/stub.logsearch-for-cf.standalone-kibana-with-auth.yml

* Drop unused port variable
* Make doppler override optional
The `firehose-to-syslog` package will use the doppler endpoint from `/v2/info` unless the user passes an override. Since that will be what users want most of the time, this patch makes the doppler override optional in `logsearch-for-cloudfoundry` as well.
cc @LinuxBozo

Drop unused ingestor settings.

---

src/kibana-cf_authentication/index.js

Using the token endpoint for authorization is incorrect and will break the session-based-redirect flow for UAA users delegating authentication to external IDPs

Use the auth endpoint for auth, and the token endpoint for tokens

---

src/logsearch-config/src/logstash-filters/snippets/app-logmessage-rtr.conf
src/logsearch-config/test/logstash-filters/it/app-it-spec.rb
src/logsearch-config/test/logstash-filters/snippets/app-logmessage-rtr-spec.rb

I found the cf-release v250+ RTR grok pattern to not working with v252 and v253. With the help of http://grokdebug.herokuapp.com I adjusted the pattern so that it works.

adds working rtr message pattern for cf release v252+

---

jobs/ingestor_cloudfoundry-firehose/spec
jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl

Enables configuration of full app metadata update interval via deployment manifest

makes cc-pull-time parameter configurable
