cloudfoundry-community/logsearch-for-cloudfoundry

- src/kibana4-dashboards/README.md
The one liner does not work for me had to remove the equal sign. Also switch to curl for fetching the file from github instead of assuming a local file.
> Does not work with = sign

- README.md
- target/logstash-filters-default.conf
Quick fix to the readme and a bad reference.
> Fix Instruction

- test/logstash-filters/snippets/doppler-spec.rb
- test/logstash-filters/snippets/vcap-spec.rb
> fix failing tests

- logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana/spec
- logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana/templates/bin/run
Signed-off-by: Alex Blease <alex@cloudcredo.com>
>  be able to set the system organisation

- logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/spec
- logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl
- logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/config/logstash.conf.erb
Hi!
This is other hand for https://github.com/logsearch/logsearch-boshrelease/pull/160
> Added ability to configure any other output instead of Redis

- src/logstash-filters/snippets/doppler.conf
- target/logstash-filters-default.conf
- test/logstash-filters/snippets/doppler-spec.rb
This can happen if you dont use HAProxy as LB,
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/NMLZERUP4PCO2OTYRBE4E3MUKSO6ELMD/
and produces massive log outputs that make logstash fill up the disk in the middle of the night..
> Dont try to geoip when remote_addr == "-"

- generate_ingestor_manifest
Hi @cromega,
this is a fix for elasticsearch_config.
Tested and proven to work.
> Fixed elasticsearch_config

- scripts/generate_deployment_manifest
- scripts/update
Hi @axelaris !
I added `scripts/update`, this script will help to keep repo and submodules up-to-date.
Also i removed Spruce binaries which were located at `bin` folder, instead of binaries, from my point of view, better to check local `Spruce` installation.
Please feel free to add any comments or questions.
Thanks!
> Add release update scripts

- config/final.yml
Hi @axelaris !
I updated endpoint for Logsearch-for-CloudFoundry S3 bucket.
Since we are maintaining this project this step is necessary for further development of the project.
Thanks!
> Update S3 bucket for release blobs

- src/logsearch-config/src/logstash-filters/snippets/haproxy.conf
1) Extend haproxy grok possible formats.
2) Check if [haproxy][http_status_code] exists before calculating `@level.`
> Haproxy grok formats + http_status_code check

- src/logsearch-config/test/filter_test_helpers.rb
- src/logsearch-config/test/logstash-filters/it/platform-it-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/haproxy-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/platform-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/setup-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/teardown-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/uaa-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/vcap-spec.rb
1) Add UTs for vcap.conf, platform.conf, setup.conf, teardown.conf;
2) Uaa & haproxy UTs: add checks for 'if' condition;
3) Improve filter_test_helpers.rb & existing tests to have more smart printing in case of errors.
> Add more UTs & improve existing some

- src/logsearch-config/.gitignore
- src/logsearch-config/Gemfile
- src/logsearch-config/Gemfile.lock
- src/logsearch-config/Rakefile
> Add YAML validation tests

- src/kibana-cf_authentication/index.js
* Filter `_search` endpoint in addition to `_msearch`
* Handle search payloads that don't include nested keys
* Handle search payloads that already include boolean filters
cc @LinuxBozo
> Filter search endpoint by org and space for non-privileged users.

- README.md
Also fixes numbering of steps in the README.
> Document Cloud Foundry configuration to forward component logs.

- .gitignore
- ci/README.md
- ci/pipeline.yml
- ci/set_pipeline
Hi!
I prefer to store secrets using Vault instead of direct yaml file. I updated pipeline and set pipeline script to use Vault backend with Spruce.
> Store Concourse CI secrets in vault

- src/logsearch-config/src/kibana4-dashboards/config/4.4.0.json.erb
- src/logsearch-config/src/kibana4-dashboards/config/4.4.2.json.erb
- src/logsearch-config/src/kibana4-dashboards/index-pattern/logs-app.json.erb
- src/logsearch-config/src/kibana4-dashboards/index-pattern/logs.json.erb
- src/logsearch-config/src/kibana4-dashboards/kibana4-dashboards.json.erb
1. Fix kibana4-dashboards.json.erb to upload Kibana index-patterns by id retrieved from json."title" instead of file name.
2. Add logs-* index-paatern.
3. Update fields of logs-app-* index pattern.
4. Add Kibana config for Kibana version used in logsearch-boshrelease (4.4.0).
> Kibana index-pattern upload

- jobs/cf-kibana/spec
- jobs/cf-kibana/templates/errand.sh.erb
- jobs/cf-kibana/templates/kibana.yml.erb
Based on https://github.com/logsearch/logsearch-boshrelease.
* Configure kibana plugins
* Add arbitrary kibana configuration
> Expose kibana plugins and arbitrary configuration variables.

- src/logsearch-config/src/logstash-filters/snippets/platform.conf
- src/logsearch-config/src/logstash-filters/snippets/teardown.conf
- src/logsearch-config/test/logstash-filters/it/platform-it-spec.rb
- src/logsearch-config/test/logstash-filters/it_platform_helper.rb
- src/logsearch-config/test/logstash-filters/snippets/platform-spec.rb
- src/logsearch-config/test/logstash-filters/snippets/teardown-spec.rb
Fix for https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/204.
> Support for cloudfoundry/syslog-release log messages

- src/kibana-cf_authentication/index.js
Fix for UAA login failing, when the oauth cookie size > 4K -- wrong redirect? #203
> Fix infinite redirect loop when uaa-oauth cookie > 4K.

- templates/stub.logsearch-for-cf.standalone-kibana-with-auth.yml
This is like https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/23 but for logsearch-for-cloudfoundry
> Add cf_vars to stub
